# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
workflows:
  version: 2
  all:
    jobs:
      - build
      - hold-for-release:
          type: approval
          requires:
            - build
      - release:
          requires:
            - hold-for-release

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      - run: ./gradlew assemble

      - store_artifacts:
          path: gong-notifier-email/build/libs
          destination: email-jars

      - store_artifacts:
          path: gong-notifier-github-pr-status/build/libs
          destination: github-pr-status-jars

      - run: ./gradlew check

      - store_test_results:
          path: gong-notifier-email/build/test-results/test

      - store_artifacts:
          path: build/reports/allTests
          destination: test-report

      - persist_to_workspace:
          root: .
          paths:
            - gong-notifier-email/build/libs/*.jar
            - gong-notifier-github-pr-status/build/libs/*.jar
            - build/version.txt

  release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: Flatten artifacts hierarchy
          command: |
            mkdir flat
            find artifacts -type f -exec cp {} flat/ \;
      - run:
          name: Publish Release on GitHub
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(cat ./flat/version.txt)
            rm -f ./flat/version.txt
            ghr -t ${GITHUB_RELEASE_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -b "Version ${VERSION}" ${VERSION} ./flat/